### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HudsonAdjetey** [HudsonAdjetey/management#1]
**Describe the bug**

**To Reproduce**
1. Go to the client page
2. Use tailwind css instead of writing a custom style for existing properties

**Expected behavior**

**Smartphone (Enhance Responsiveness for the following devices resolution):**

**Comment by KnightH121** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to the client page
> 2. Use tailwind css instead of writing a custom style for existing properties
> 
> **Expected behavior**
> 
> **Smartphone (Enhance Responsiveness for the following devices resolution):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]

Posted
